# Generated by Django 5.2 on 2025-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Project Lead', 'Project Lead'), ('Developer', 'Developer'), ('Client', 'Client')], max_length=50, default='Client'),
        ),
    ]
