# Generated by Django 5.2 on 2025-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Project Lead', 'Project Lead'), ('Developer', 'Developer'), ('Client', 'Client')], max_length=50),
        ),
    ]
